### ISSUE TITLE
Using T within a JS promise.

### ISSUE THREAD

**Issue by qroft** [mntn-dev/t.js#10]
I am absolutely new to the JS promise solution, so please forgive me if i am missing here something. The following code just shows the first two t.js texts - the third does not appear though all Alerts (if uncommented) do work. Am i misusing the 'add' function of t.js ?

```
          new Promise(function(resolve, reject) {
            $('#logger').t('Starting import function.<br>',{
              beep: true,
              speed:20,
              repeat:false
            });
            setTimeout(() => resolve(1), 2000);
          }).then((result) => {
            $('#logger').t('add','Starting import function.<br>');
            //alert(result);
            return result + 2;
          }).then((result) => {
            $('#logger').t('add','Another text.<br>');
            //alert(result);
            return result + 2;
          }).then((result) => {
            $('#logger').t('add','yet antoher text.<br>');
            ///alert(result);
            return result + 2;
          });

```

**Comment by mntn-dev** [comment]
hi,

looks like **t.js** is _still_ typing (check `$('#logger').data().is_typing`), so new to-type-content will be rejected (doesn't stack/process by default). here's a `setInterval`-wrapped `.push`/`.shift`-workaround:
[t-stack.htm](https://mntn-dev.github.io/t.js/t-stack.htm)

**Comment by mntn-dev** [comment]
**FYI**
as of v1.5.4, queued type processing is now built-in --
`$(elm).t('queue',content)` (shorthand: `$(elm).q(content) `)
