### ISSUE TITLE
Does not run on mobile (iOS/Safari-13)

### ISSUE THREAD

**Issue by spoofzu** [mntn-dev/t.js#11]
Any idea why this might not run on iPhone (version 13.3.1)?  I thought it was my JS script but I tried your page, mntn-dev.github.io/t.js, and noticed the same behavior.  Locked cursor that does not move.  Runs great with desktop browsers, good job btw.  

I Realize you have better ways to spend your time but if you could share a couple ideas for me to pursue that would be great.  Thanks.

**Comment by spoofzu** [comment]
A few updates.  Does not work with MAC OSX Safari Version 13.0.5 (15608.5.11).  Generally works well with desktop version of FF and Chrome.  A head scratcher.  Well that's JS.  ;o)

**Comment by mntn-dev** [comment]
hi,

since Apple doesn't provide (recent) Windows versions of their Safari browser anymore, i can't tinker well. anything the __Web Inspector__ says? (error logs, ...)

does [demo.htm](https://mntn-dev.github.io/t.js/demo.htm) also fail? have you tried both, `beep:false` and `beep:true`?

**Comment by mntn-dev** [comment]
please check [t-debug.htm](https://mntn-dev.github.io/t.js/t-debug.htm) --

![t-debug](https://user-images.githubusercontent.com/4998331/79719333-a02ee580-82de-11ea-956f-a7eb211ac363.gif)

**Comment by mntn-dev** [comment]
ok, did some tests at [Appertize](https://appetize.io/demo?device=iphonex&scale=75&orientation=portrait&osVersion=13.3) - looks like a __WebAudio/iOS13__-related browser issue (also mentioned [here](https://github.com/mrdoob/three.js/issues/18654#issuecomment-591309712) and [there](https://bugs.webkit.org/show_bug.cgi?id=203435)).

silent/`beep`-less typing (check __[t-debug.htm?beep0](https://mntn-dev.github.io/t.js/t-debug.htm?beep0)__) should work/run.

---

meanwhile... skip `beep` for  __iOS 13.3__ w/ [mobile-detect.js](https://github.com/hgoebl/mobile-detect.js):

`<script src="https://cdn.jsdelivr.net/npm/mobile-detect@1.4.4/mobile-detect.min.js"></script>`

```
var md=new MobileDetect(window.navigator.userAgent);

$(function(){
 $(elm).t({
  beep:((/13\.3/.test(md.version('iOS')))?false:true)
  //[...]
 });
});
```

**Comment by spoofzu** [comment]
That was it.  Turned off the sound, Success!  Appreciate the tips/workaround.

A bonus question, not a show stopper or problem with t.js but I'll ask since your know your JS well.  I have the terminal running in a page.  Is there an easy way to know when the script execution is complete for the page?    Events like on page load are useless.  Setting a boolean in the script at the bottom of the page does not work since script sections execute asynchronous will all the other scripts on the same page.  The reason I ask is that I start a timer and call,
window.scrollTo(0,document.body.scrollHeight);
every 250ms to scroll the page to the bottom, so the page can be viewed as it's typed.  If the answer does not come easy or your don't understand my question don't worry about it.  Appreciate your assistance.

**Comment by mntn-dev** [comment]
>  [...] when the script execution is complete [...]

i recommend to set the to-type-content's `CSS` to `display:none` (or `visibility:hidden`) which avoids flashing while page/script-loads is active.

btw, i recommend `bottom:0` for the (to-type-)container's CSS, __or__, capturing a newline via _t.js'_ `typing` callback and exec `.scrollTop` then. 

see:

* [t-scroll.htm](http://mntn-dev.github.io/t.js/t-scroll.htm)
* [t-bottom.htm](http://mntn-dev.github.io/t.js/t-bottom.htm)
