### ISSUE TITLE
non jQuery version?

### ISSUE THREAD

**Issue by Lewiscowles1986** [mntn-dev/t.js#14]
Hi,

Unless I'm misunderstanding this requires jQuery. Do you know of any versions without that dependency? 

Best,
Lewis

**Comment by mntn-dev** [comment]
no, jQuery is req'd from the beginning -- v0.0001.
anyway, there are other, non-dependencies Typers you might want to try:
* [@typewriterjs](https://github.com/tameemsafi/typewriterjs)
* [@typed.js](https://github.com/mattboldt/typed.js/)
