### ISSUE TITLE
-- nested <del>

### ISSUE THREAD

**Issue by keebOo** [mntn-dev/t.js#4]
Hi,
could be possible add the feature of nested <del> ?

(I add an example based on the demo code)

`<div id="t"><del><strong>Hello.</strong><ins>0.5</ins> This is <em>t.js</em>, a<del> heavy <ins>3</ins>...sorry  I mean <ins>1</ins><s>black,white</s></del><kbd> lightweight</kbd> jQuery typewriter script.
<br/><button id="btn1">Learn more</button></del>`

I'd like to run all and at the end delete everything, to start in the same space with other text.

**Comment by keebOo** [comment]
To be clear: without using `<del>*</del> `but only an entire block.

**Comment by mntn-dev** [comment]
here's a (dirty) workaround for both, nested &lt;del&gt; and multiple &lt;ins&gt; based on [ZW(N)J](https://en.wikipedia.org/wiki/Zero-width_joiner) triggering:

https://mntn-dev.github.io/t.js/del-hack.htm
(see source)

**Comment by keebOo** [comment]
Thanks, 
dirty and fast jquery solution ;)
I have long text and I'll use this workaround to make a custom function to manage these cases.

Thanks again.
