### ISSUE TITLE
-- "t is not a function" (differences between bower version and old one)

### ISSUE THREAD

**Issue by keebOo** [mntn-dev/t.js#5]
Hi,
I hope to explain corretcly, this is what happen:

- have a t.js manually added to a project **[OK]**
- create a new project download/install with bower
- check all path files (new project with same files of old one)
- javascript error "t is not a function" **[ERROR]**
- copy manually the old t.js overwriting the new one from bower in the new project **[OK]**

line of my code code where is first call to library
```
function writecell(cellindex, text, fast)
	{
		if (fast){
			$(".tableresult td").eq(cellindex).html(text);	
		}
		else
		{
			$(".tableresult td").eq(cellindex).html("").t(text,{
				speed:40,
				speed_vary:true,
				blink: 400,
				fin:function(){
					window.setTimeout(function()
					{
						$(".tableresult td").eq(cellindex).html(text);
					},1000);
					
				}
			});
		}
	}
```

first lines of your t.js (old and new from bower, hope could be useful to understand what I'm using)

START OF NEW ONE
```
/*
		 _     _
		| |   (_)
		| |_   _ ___
		| __| | / __|
		| |_ _| \__ \
		 \__(_) |___/
		     _/ |
		    |__/

	t.js
	a micro-templating framework in ~400 bytes gzipped

	@author  Jason Mooberry <jasonmoo@me.com>
	@license MIT
	@version 0.1.0

*/
!function(){function n(n){this.t=n}function r(n){return new Option(n).innerHTML.replace(/"/g,"&quot;")}function t(n,r)

```
START OF OLD ONE 
`/*t.js-0.5;(c)2014 Mntn(r) <http://mn.tn/> c/o Benjamin Lips <g--AT--mn.tn>;Licensed under the MIT License <http://mit-license.org/>;For documentation see http://github.com/mntn-dev/t.js or http://mn.tn/dev/t.js*/(function(d){d.fn.t=function(v,w){return this.each(function(){var a=w,h=v,b=d(this),n,q,k=!1,p="12qwertyuiop[]asdfghjkl;zxcvbnm,./~!@#$%^&*()_+:1234567890-=op"`

**Comment by mntn-dev** [comment]
eh.. Jason Mooberry's _t.js_ isn't related to my typewriter script in any way. some bower rattle case? btw, upgrade to t.js-0.9.

**Comment by keebOo** [comment]
ooopssss!! 
Sorry a lot... just see now...  for this reason doesn't run!!

:D 

![schermata 2017-10-31 alle 12 08 32](https://user-images.githubusercontent.com/2150191/32221034-453a7d0e-be34-11e7-8dfa-8b507774bc40.png)

**Comment by keebOo** [comment]
Listen, I'm kind of embarrassed about previous issue.... but... I'd like something more... :)

I just overwriting 0.5 with 0.9, but get an error on "blinking" from my function write before on this issue: seems that if I overwrite on the cell, after typing with your t.js (many cells, to many blinking cursor, this was my workaround solution), 0.9 give me an error in console because doesn't find the "blinking" ... correct obviously.

The 0.5 doesn't do this, seems ignore it.

Anyway... thanks for patience.

**Comment by mntn-dev** [comment]
blink-(set)interval's ID is stored in elm's `.data()`, try `clearInterval($('#elm').data('bi'))`
or, to just stop blinking: `$('#elm').data('blinking',0)`
or, hide the caret: `$('#elm').find('.t-caret').css({opacity:0});`

**Comment by keebOo** [comment]
Perfect.
Thanks, as usual.
