### ISSUE TITLE
write in plain text

### ISSUE THREAD

**Issue by samuelesantoni** [mntn-dev/t.js#7]
Is possible write in plain text? I would like write html code. Thanks.

**Comment by mntn-dev** [comment]
could you be more specific?

**Comment by samuelesantoni** [comment]
i created a windows like an html editor and inside i would like type the html code...have you understand? :)

**Comment by mntn-dev** [comment]
hi,

can you provide a HTML file by way of illustration?

**Comment by samuelesantoni** [comment]
You can see my pen: https://codepen.io/eleumas/pen/erEjWg

Thanks.

**Comment by mntn-dev** [comment]
your pen didn't work  because `t.js` was loaded before `jquery` (see source);
also, the `uikit` framework (not familiar with this) seems to require an sub elem here in order to work - i've added `<div id="text_"...>`

checkout -- https://codepen.io/anon/pen/degMyY
