### ISSUE TITLE
AudioContext not supported on Safari 

### ISSUE THREAD

**Issue by corgoss** [mntn-dev/t.js#8]
On safari version 11.1.2 t.js is crashing because safari cant find audioContext .

**Comment by mntn-dev** [comment]
Browser issue. Chrome also deactivated autoplay (however, without _crashing_), but reactivated in current version. everything works if `{..., beep: false}`? 

from [SO](https://stackoverflow.com/a/46534088):
> (...) Safari on iOS 11 seems to automatically __suspend new AudioContext__'s that aren't created in response to a __tap__. 

try my [Fiddle](http://jsfiddle.net/4v8xLmo2/5/) to see if a preceded click/tap solves

**Comment by mntn-dev** [comment]
[v1.2](https://raw.githubusercontent.com/mntn-dev/t.js/master/t.js) is out -- `AudioContext` now considers the [Safari-required](https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/PlayingandSynthesizingSounds/PlayingandSynthesizingSounds.html#//apple_ref/doc/uid/TP40009523-CH6-SW2) `webkit` prefix.

> `__TAC=(window.AudioContext=(window.AudioContext||window.webkitAudioContext))?new AudioContext():!1)`
