### ISSUE TITLE
Change Speed at runtime

### ISSUE THREAD

**Issue by vikramjits** [mntn-dev/t.js#9]
Hi,

Is there a way to update the speed at runtime (just like 'beep'), so that we can make the typing faster or slower while typing is going on?

Thanks

**Comment by mntn-dev** [comment]
hi,

it's not implemented; however, here's a little workaround:
[@speed-change-hack.htm](https://mntn-dev.github.io/t.js/speed-change-hack.htm) (see source)

there are other js-typewriters out there which have it built-in, like:
* [typish](https://github.com/rstacruz/typish) `type(text, [element, speed])`
* [Typewriter](https://github.com/tameemsafi/typewriterjs) `changeDelay`
* [Typewrite](https://github.com/mrvautin/typewrite) `{speed: x}`

**Comment by mntn-dev** [comment]
as of v1.5.1, it's now also a **t.js** feature; either via html-tag (`<s>speed_in_ms</s>`) or method (`$(elm).s(speed_in_ms)`).

**Comment by vikramjits** [comment]
Thanks a lot! this is working perfect :)
